language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_install: ./travisscripts/travis-before-install.sh

install: mvn install -Dgpg.skip=true

notifications:
  email:
    recipients:
      - hendrikdev22@gmail.com
    on_success: always
    on_failure: always
